# Generated by Django 5.2.4 on 2025-08-09 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('selected_answer', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cbt_app.examsession')),
            ],
        ),
    ]
