# Generated by Django 5.2.4 on 2025-08-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0002_examsession_end_time_examsession_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='start_time',
        ),
        migrations.DeleteModel(
            name='ExamAnswer',
        ),
    ]
