# Generated by Django 5.2.4 on 2025-08-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0004_question_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
    ]
