# Generated by Django 5.2.4 on 2025-08-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0005_remove_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='adaptive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='asked_question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='examsession',
            name='correct_streak',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examsession',
            name='current_difficulty',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='examsession',
            name='incorrect_streak',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examsession',
            name='total_questions',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=2),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
