# Generated by Django 5.2.4 on 2025-08-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0006_examsession_adaptive_examsession_asked_question_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='total_questions',
        ),
    ]
