# Generated by Django 5.2.4 on 2025-08-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0007_remove_examsession_total_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='pending_question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
