# Generated by Django 5.2.4 on 2025-08-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0008_examsession_pending_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
