# Generated by Django 5.2.4 on 2025-08-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0009_examsession_ends_at_examsession_finished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
