# Generated by Django 5.2.4 on 2025-08-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0010_exam_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
